media: public/news_images

content:
  - name: news
    label: News
    type: json
    path: src/data/news.json
    list: true
    fields:
      - name: newsTitle
        label: Title
        type: string
        required: true
        
      - name: newsDate
        label: Date
        type: string
        required: true
        
      - name: newsPic
        label: Image
        type: image
        
      - name: newsData
        label: Content
        type: rich-text